version: "3"
services:
  web:
    build: .
    ports:
      - "1234:1234"
    environment:
      - CONNECTION_STR=root:root@tcp(db:3306)/database?charset=utf8&parseTime=True&loc=Local
    depends_on:
      - db
  db:
    image: mariadb
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
